### PR TITLE
Add option for 95% (2 Sigma) limits

### PR DESCRIPTION
**Pull request by andrjohns**
Hi Jacob,

This PR adds the calculation of and option to show 2 sigma limits on the generated SPC plot. The option is off by default, so there should be no changes to existing behaviour.

The `testthat` `.rds` references will need to be re-generated to include the output of the 95% limits, but I've just excluded those limits from the tests at the moment so that you can see that all existing tests pass.

Let me know if I've missed anything.

Thanks!
Andrew

### CODE REVIEW

**Review by anhoej — COMMENTED** [review]
Thanks! I am right in that these additions "only" add 2 sigma limits to plots and do not include any new test, e.g 4 out of 5 data points outside 2 sigma? Not that I am against the latter, but just to make sure.

**Comment by andrjohns** [comment]
Yep! No changes to rules or checking. This just adds the 2 sigma limits to the dataframe, plot, and summary

**Comment by anhoej** [comment]
Thanks. Good idea. I'll have a closer look.

**Comment by anhoej** [comment]
Looks good. May I suggest you add 3s lines in the same colour as 2s lines, when show.95 = T. That would make it easier not to misinterpret 2s lines as 3s, which is a risk when 3s is only shown as gray background. Try options(cl.shade = F) to see what I mean.

**Pull request merged**
